### ISSUE TITLE
Test local GPS

### ISSUE THREAD

**Issue by mcules** [SamuelBrucksch/open360tracker#19]
Local GPS has to be implemented

**Comment by SamuelBrucksch** [comment]
Its already implemented. We do not need tasks for testing.

**Comment by MarenB** [comment]
Hi there,

the config.h still says, that UBX is not implemented, yet - is that still valid? Or has it been implemented in the meantime, just like you did for the DIY-FrSky-GPS?

THX

**Comment by SamuelBrucksch** [comment]
Not implemented. This was closed because testing is no issue.
