### ISSUE TITLE
RSSI fallback

### ISSUE THREAD

**Issue by MarenB** [SamuelBrucksch/open360tracker#26]
Just a proposal:
the system could fall back to RSSI-based tracking in case of lost or no telemetry connection.
A similar solution can be found here: http://fpv-community.de/showthread.php?6588-ArduFrSky-Antennen-Tracker

**Comment by SamuelBrucksch** [comment]
if someone is eager to implement RSSI tracking then he can do it, but as i do not think RSSI trackers are accurate i will not do it.
